solenoid_open_time_sec:                 30
solenoid_close_time_sec:                30

vent_pressure_start_psi:                900
vent_pressure_stop_psi:                 600

/hardware/abort_valve/pin_a:            "P9_11"
/hardware/abort_valve/pin_b:            "P9_12"

/hardware/ematch/pin_a:                 "P9_13"
/hardware/ematch/pin_b:                 "P9_15"
/hardware/ematch/delay:                 0.3

/hardware/injection_valve/pin_a:        "P9_18"
/hardware/injection_valve/pin_b:        "P9_17"

/hardware/linear_actuator/pin_a:        "P9_24"
/hardware/linear_actuator/pin_b:        "P9_23"

/hardware/solenoid/pin:                 "P9_26"
/hardware/solenoid/opened:              30
/hardware/solenoid/closed:              30

# sensor pins and polling periods, in seconds
/sensors/combustion_thermocouple_1/pin:     "AIN1"
/sensors/combustion_thermocouple_1/period:  1
/sensors/combustion_thermocouple_2/pin:     "AIN2"
/sensors/combustion_thermocouple_2/period:  1
/sensors/combustion_transducer/pin:         "AIN3"
/sensors/combustion_transducer/period:      0.25
/sensors/ox_tank_thermocouple/pin:          "AIN4"
/sensors/ox_tank_thermocouple/period:       1
/sensors/ox_tank_transducer/pin:            "AIN5"
/sensors/ox_tank_transducer/period:         0.25
/sensors/float_switch/pin:                  "AIN6"
/sensors/float_switch/period:               0.25

commands:
- read data:                            "all"
- read data .*:                         "all"
- stop data:                            "all"
- read voltage:                         "all"
- read voltage .*:                      "all"
- stop voltage:                         "all"
- listen to .*:                         "all"
- stop listening to .*:                 "all"
- stop listening all:                   "all"
- rosnode list:                         "all"
- rostopic list:                        "all"
- uptime:                               "all"
- print readiness level:                "all"
- elevate readiness:                    "all"
- reduce readiness:                     "all"
- print whitelist:                      "all"
- system .*:                            "all"
- timeout:                              "all"
- timeout .*:                           "all"
- fork .*:                              "all"

- all stop:                             "all"
- abort:                                "all"

- driver help:                          "all"
- driver .*:                            []

- begin fill:                           [2]
- end fill:                             [2, 3]
- launch:                               [9]

